name: MRE-PINN
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - scikit-image
  - pandas
  - xarray
  - cudatoolkit=11.3
  - pytorch::pytorch>=1.12.1
  - torchvision
  - deepxde
  - fenics-dolfinx
  - petsc=*=complex*
  - netCDF4
  - matplotlib
  - seaborn
  - notebook
  - ipykernel
  - ipywidgets
  - tqdm
  - parse

